version: '3.4'

services:
  portainer:
    image: portainer/portainer-ce

  cardsdb:
    image: mongo

  cards.api:
    image: ${DOCKER_REGISTRY-}cardsapi
    build:
      context: .
      dockerfile: EXPENSE/Cards/Cards.API/Dockerfile
volumes:
  mongo_data:
  portainer_data: