version: '3.4'

services:
  cardsdb:
    container_name: cardsdb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
  cards.api:
    container_name: cards.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://cardsdb:27017"
    depends_on:
      - cardsdb
    ports:
      - "8000:80"
   
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "8500:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
