version: '3.4'

services:
  cardsdb:
    container_name: cardsdb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  expensedb:
    container_name: expensedb
    environment:
        SA_PASSWORD: 'SqlServer@2019'
        ACCEPT_EULA: 'Y'
    restart: always
    ports:
        - '1433:1433'

  cards.api:
    container_name: cards.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://cardsdb:27017"
    depends_on:
      - cardsdb
    ports:
      - "8000:80"
   
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "8500:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  expense.api:
    container_name: expense.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=expensedb;Database=ExpenseDb;User Id=sa;Password=SqlServer@2019"
    depends_on:
        - expensedb
    ports:
        - "8001:80"


  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
        - cards.api
        - expense.api
    ports:
        - "8010:80"

