version: '3.4'

services:
  cardsdb:
    container_name: cardsdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  cards.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://cardsdb:27017"
    depends_on:
      - cardsdb
    ports:
      - "8000:80"
