version: '3.4'

services:
  portainer:
    image: portainer/portainer-ce

  cardsdb:
    image: mongo
  
  expensedb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  cards.api:
    image: ${DOCKER_REGISTRY-}cardsapi
    build:
      context: .
      dockerfile: EXPENSE/Cards/Cards.API/Dockerfile
  expense.api:
    image: ${DOCKER_REGISTRY-}expenseapi
    build:
      context: .
      dockerfile: EXPENSE/Expenses/Expense.API/Dockerfile

  ocelotapigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: EXPENSE/OcelotApiGw/Dockerfile

volumes:
  mongo_data:
  portainer_data:

